fix-only = true

[format]
skip-magic-trailing-comma = true

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true
