name: Build

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

run-name: Build from ${{ github.ref }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: 1.75.0
          components: rustfmt clippy

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install LLVM
        uses: ./.github/actions/install-llvm
        with:
          os: "ubuntu-20.04"
          version: "15"

      - name: Build
        run: |
          pwsh ./build.ps1
        shell: pwsh